version: '3.9'

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
    driver: local
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: "npm start"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M